config/routes.rb
Rails.application.routes.draw do

  # ユーザー側
  # URL /customers/sign_in ...
  devise_for :user,skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # ゲストユーザー側
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    # get 'user', to: 'public/registrations#new'
  end

  # 管理者側
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }

  # ユーザー側
  scope module: :public do
    root to: 'homes#top'
    get 'group_messages/create'
    get '/about' => 'homes#about'
    get '/genre/search' => 'music_posts#index'
    # お問い合わせ
    resources :contacts, only: [:new, :index, :create]
    # 探究室
    resources :labos, only: [:index, :show, :create, :update, :destroy] do
      resources :labo_comments, only: [:create,:destroy]
    end
    # tagと紐づけを行うためのlabo
    resources :tags do
      member do
        get :labos
        delete :labo
      end
    end

    # 音楽共有
    resources :music_posts, only: [:index, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only: [:index, :create, :destroy]
      resources :music_post_comments, only:[:create, :destroy, :update]
    end

    # ユーザー情報

    resources :users, only: [:show, :edit, :update, :index] do
      # 退会確認画面
      get 'confirm', on: :member
      # フォロー・フォロワー
      member do
        get 'followings'
        get 'followers'
      end

      # ユーザー検索用
      # コレクションの中に入れることでidを渡さずにパスを生成してくれる
      collection do
        get 'search'
         # 論理削除用のルーティング
        patch  'withdraw'
      end
      # いいね一覧表示
      member do
        get 'favorites'
      end
      post 'user_music_posts', to: 'user_music_mosts#create', as: 'user_music_posts'

      resources :nikos, only: [:create, :update, :destroy]
      resource :relationships, only: [:create, :destroy]
    end
    # グループ
    resources :groups, only: [:index, :show, :create, :update, :edit, :create, :destroy] do
      get 'join' => 'groups#join'
      delete 'leave', on: :member
      resources :group_user_comments, only: [:create, :destroy]
    end
  end

  # 管理者側
  namespace :admin do
    root to: 'homes#top'
    # 検索用
    get '/search' => 'homes#search'
    # お問い合わせ
    resources :contacts, only: [:index, :show]
    # 会員情報
    resources :users, only: [:index, :show, :edit, :destroy, :update] do
      resources :user_post_comments, only: [:index, :destroy]
      get '/comments' => 'user_comments#comment'
      member do
        patch '/comments' => 'comments#update'
        delete '/comments' => 'comments#destroy'
      end
    end
    # グループ
    resources :groups do
      resources :group_users, only: [:index] do
        delete 'destroy', to: 'group#destroy', as: 'group_destroy'
        resources :group_user_comments, only: [:index, :show, :destroy]
      end
    end
    # 探究室コメント
    resources :labos, only: [:index, :show, :create, :update, :destroy] do
      resources :labo_comments, only: [:index, :destroy, :show]
    end
    #resources :labo_comments, only: [:index, :show, :destroy]
    # タグ一覧・作成
    resources :tags, only: [:index, :create, :edit, :update, :destroy] do
      delete 'destroy_all', on: :collection
    end
    # 音楽共有
    resources :music_posts, only: [:index, :show, :destroy] do
      resources :music_post_comments, only:[:index, :destroy]
    end
    #resources :music_post_comments, only: [:index, :show, :destroy]
  end
end

app/models/labo.rb
class Labo < ApplicationRecord

  # タグ/探究室と探究コメントを繋ぐ
  has_many :tag_labos, dependent: :destroy
  has_many :tags, through: :tag_labos
  has_many :labo_comments, dependent: :destroy
  belongs_to :user

  validates :body, presence: true, length: { maximum: 200 }
  validates :tags, presence: true
end

app/controllers/admin/labos_controller.rb
class Admin::LabosController < ApplicationController
  before_action :authenticate_admin!

  def index
    @labos = Labo.all
  end

  def show
    @labo = Labo.find(params[:id])
    @labo_comments = @labo.labo_comments
    @user = @labo.user
    @tags = @labo.tags
  end

  def destroy
    @labo = Labo.find(params[:id])
    @labo.destroy
    redirect_to admin_labos_path, notice: "探究室の投稿を削除しました。"
  end
end

app/helpers/admin/labos_helper.rb
module Admin::LabosHelper
end

app/views/admin/labos/index.html.erb
<!--探究室一覧-->
<div class="container my-4 pb-5">
  <div class="row  justify-content-start mb-2">
    <h5 class="style-title">探究室一覧</h5>
  </div>
  <div class="row custom-background">
    <div class="col-2">
      <h5>日付</h5>
    </div>
    <div class="col-4 text-left">
      <h5>タグ</h5>
    </div>
    <div class="col text-left">
      <h5>投稿文</h5>
    </div>
  </div>

  <% @labos.each do |labo| %>
  <div class="row custom-table-striped border border-danger">
    <div class="col-2 text-center my-3 ">
      <h5><%= labo.created_at.strftime('%Y/%m/%d') %></h5>
    </div>
    <div class="col-4 text-left my-3">
    <% labo.tags.each do |tag| %>
      <%= tag.title %><br>
    <% end %>
    </div>
    <div class="col text-left my-3">
      <h5><%= link_to labo.body, admin_labo_path(labo.id), class: "style-color" %></h5>
    </div>
  </div>
  <% end %>
  <%#= paginate @labo_pages %>
</div>

app/views/admin/labos/show.html.erb
<!--探究室の投稿詳細-->
<div class="container my-4 pb-5">
  <div class="row justify-content-start mb-3">
    <h5 class="style-title">会員ID:<%= @user.id %> <%= @user.nickname %> さんの探究室投稿内容</h5>
  </div>

  <div class="row custom-background">
    <div class="col-2"></div>
    <div class="col-4 text-left">
      <h5>タグ</h5>
    </div>
    <div class="col text-left">
      <h5>質問内容</h5>
    </div>
  </div>

  <div class="row d-flex align-items-center justify-content-centerborder border border-danger">
    <div class="col-2 my-3">
      <%= image_tag @user.get_profile_image, class: "rounded-circle", size: '100x100' %>
    </div>
    <div class="col-4 text-left">
      <% @tags.each do |tag| %>
      <div class="flex-colmum">
        <%= tag.title %>
      </div>
      <% end %>
    </div>
    <div class="col text-left">
      <%= @labo.body %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col text-right">
      <%= link_to "投稿削除", admin_labo_path(@labo.id), method: :delete, class: "btn btn-danger", data: { confirm: "本当に削除しますか？"}, remote: true %>
    </div>
  </div>

  <div class="row my-3">
    <div class="col text-right">
      <%= link_to "探究室一覧へ戻る", admin_labos_path, class: "btn text-white admin-background-btn" %>
    </div>
  </div>

<!--探究室の投稿コメントが表示される-->
<% if @labo.labo_comments.exists? %>
  <div class="row my-4">
    <h5 class="style-title">投稿のコメント</h5>
  </div>
  <div class="row mt-2 custom-background">
    <div class="col-3"></div>
    <div class="col text-left mt-1">
      <h5>コメント</h5>
    </div>
    <div class="col-2 mt-1" style="display: block;">
      <h5>回答者</h5>
    </div>
  </div>

  <div class="row d-flex align-items-center justify-content-center border border-danger">
  <% @labo_comments.each do |labo_comment| %>
    <div class="col-12 custom-table-striped border border-danger">
      <div class="row my-1">
        <div class="col-3 text-left ml-2 d-flex align-items-center">
          <%= link_to "コメント削除", admin_labo_labo_comment_path(labo_comment.labo, labo_comment), method: :delete, class: "btn btn-danger now-nowrap", data: { confirm: "本当に削除しますか？"}, remote: true %>
        </div>
        <div class="col text-left d-flex align-items-center">
          <%= labo_comment.comment %>
        </div>
        <div class="col-2 mr-auto flex-colmum mr-2 my-3">
        <%= image_tag labo_comment.user.get_profile_image, class: "rounded-circle", size: "50x50" %>
          <div class="flex-colmum">
          <%= link_to labo_comment.user.nickname, admin_user_path(labo_comment.user), class: "style-color" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% else %>
  <div class="row my-5">
    <div class="col" style="solid #F07C81; color: #000000;">
      <h5>まだ　<b><%= @labo.user.nickname %></b>　さんの質問に誰も回答されていません。</h5>
    </div>
  </div>
<% end %>
</div>