config/routes.rb
Rails.application.routes.draw do

  # ユーザー側
  # URL /customers/sign_in ...
  devise_for :user,skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # ゲストユーザー側
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    # get 'user', to: 'public/registrations#new'
  end

  # 管理者側
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }

  # ユーザー側
  scope module: :public do
    root to: 'homes#top'
    get 'group_messages/create'
    get '/about' => 'homes#about'
    get '/genre/search' => 'music_posts#index'
    # お問い合わせ
    resources :contacts, only: [:new, :index, :create]
    # 探究室
    resources :labos, only: [:index, :show, :create, :update, :destroy] do
      resources :labo_comments, only: [:create,:destroy]
    end
    # tagと紐づけを行うためのlabo
    resources :tags do
      member do
        get :labos
        delete :labo
      end
    end

    # 音楽共有
    resources :music_posts, only: [:index, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only: [:index, :create, :destroy]
      resources :music_post_comments, only:[:create, :destroy, :update]
    end

    # ユーザー情報

    resources :users, only: [:show, :edit, :update, :index] do
      # 退会確認画面
      get 'confirm', on: :member
      # フォロー・フォロワー
      member do
        get 'followings'
        get 'followers'
      end

      # ユーザー検索用
      # コレクションの中に入れることでidを渡さずにパスを生成してくれる
      collection do
        get 'search'
         # 論理削除用のルーティング
        patch  'withdraw'
      end
      # いいね一覧表示
      member do
        get 'favorites'
      end
      post 'user_music_posts', to: 'user_music_mosts#create', as: 'user_music_posts'

      resources :nikos, only: [:create, :update, :destroy]
      resource :relationships, only: [:create, :destroy]
    end
    # グループ
    resources :groups, only: [:index, :show, :create, :update, :edit, :create, :destroy] do
      get 'join' => 'groups#join'
      delete 'leave', on: :member
      resources :group_user_comments, only: [:create, :destroy]
    end
  end

  # 管理者側
  namespace :admin do
    root to: 'homes#top'
    # 検索用
    get '/search' => 'homes#search'
    # お問い合わせ
    resources :contacts, only: [:index, :show]
    # 会員情報
    resources :users, only: [:index, :show, :edit, :destroy, :update] do
      resources :user_post_comments, only: [:index, :destroy]
      get '/comments' => 'user_comments#comment'
      member do
        patch '/comments' => 'comments#update'
        delete '/comments' => 'comments#destroy'
      end
    end
    # グループ
    resources :groups do
      resources :group_users, only: [:index] do
        delete 'destroy', to: 'group#destroy', as: 'group_destroy'
        resources :group_user_comments, only: [:index, :show, :destroy]
      end
    end
    # 探究室コメント
    resources :labos, only: [:index, :show, :create, :update, :destroy] do
      resources :labo_comments, only: [:index, :destroy, :show]
    end
    #resources :labo_comments, only: [:index, :show, :destroy]
    # タグ一覧・作成
    resources :tags, only: [:index, :create, :edit, :update, :destroy] do
      delete 'destroy_all', on: :collection
    end
    # 音楽共有
    resources :music_posts, only: [:index, :show, :destroy] do
      resources :music_post_comments, only:[:index, :destroy]
    end
    #resources :music_post_comments, only: [:index, :show, :destroy]
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @total_active_users = User.where(is_active: true).size
    @total_inactive_users = User.where(is_active: false).size
    @total_users = User.all.size
    @groups = Group.order('id DESC').limit(4)
    @music_posts = MusicPost.order('id DESC').limit(4)
    @labos = Labo.order('id DESC').limit(4)
  end
  
  def search
    # @model = params[:model]
    # @content = params[:content]
    # @method =params[:method]

    # # 選択したモデルに応じて検索を実行
    # if @model == 'user'
    #   @records = User.search_for(@content, @method)
    # else
    #   @records = MusicPost.search_for(@content, @method)
    # end
    if params[:search]
      @users = User.where('nickname LIKE ?', "%#{params[:search]}%")
      @user_page = User.page(params[:page])
    else
      @users = User.all
      @user_page = User.page(params[:page])
    end
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/search.html.erb
<div class="container mb-5 pb-5">
  <div class="row my-3">
    <h5 class="style-title">会員検索一覧</h5>
  </div>
  <div class="row">
    <div class="col">
      <% @users.each do |user|%>
      <div class="row custom-table-striped border border-danger">
        <div class="col-2 my-2 text-left">
          <%= image_tag user.get_profile_image, size: "50x50", class: "custom-border" %>
        </div>
        <div class="col-3 text-left d-flex align-items-center">
          <%= link_to user.nickname, admin_user_path(user.id), class: "style-color" %>
        </div>
        <div class="col text-left d-flex align-items-center">
          <h6><%= user.introduction %></h6>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container my-4 pb-5">
  <div class="admin-top">
    <div class="row mt-2">
      <div class="col">
        <div class="col mb-5">
          <div class="row">
            <div class="col text-right align-bottom">
              <h5 class="admin-title">サイト利用者数</h5>
            </div>
            <div class="col text-left align-bottom">
              <h5 class="admin-color">計 :<%= @total_users %>人</h5>
            </div>
          </div>

          <div class="row">
            <div class="col text-right align-bottom">
              <h5 class="admin-title">登録している人</h5>
            </div>
            <div class="col text-left align-bottom">
              <h5 class="admin-color">計 :<%= @total_active_users %>人</h5>
            </div>
          </div>
          <div class="row">
            <div class="col text-right align-bottom">
              <h5 class="admin-title">退会した人</h5>
            </div>
            <div class="col text-left align-bottom">
              <h5 class="admin-color">計 :<%= @total_inactive_users %>人</h5>
            </div>
          </div>

          <div class="row mt-3 custom-background">
            <div class="col mt-2 text-left align-bottom">
              <h5>新規グループ名</h5>
            </div>
          </div>
          <% @groups.each do |group| %>
          <div class="row custom-table-striped border border-danger">
            <div class="col-4 text-left my-2">
              <h5><%= link_to group.name, admin_group_path(group.id), class: "style-color" %></h5>
            </div>
            <div class="col mt-2 text-left">
              <%= group.body %>
            </div>
          </div>
          <% end %>
          <div class="row mt-4 custom-background">
            <div class="col-4 mt-2 align-bottom text-left">
              <h5>音楽共有の新規投稿</h5>
            </div>
          </div>
          <% @music_posts.each do |music_post| %>
          <div class="row custom-table-striped border border-danger">
            <div class="col-4 my-2 text-left align-middle">
              <%= link_to music_post.title, admin_music_post_path(music_post.id), class: "style-color" %>
            </div>
            <div class="col my-2 text-left">
              <%= music_post.body %>
            </div>
          </div>
          <% end %>
          <div class="row mt-4 custom-background">
            <div class="col mt-2 text-left">
              <h5>探究室の新規投稿</h5>
            </div>
          </div>
          <% @labos.each do |labo| %>
            <div class="row custom-table-striped border border-danger">
              <div class="col text-left my-2">
                <%= link_to labo.body, admin_labo_path(labo.id), class: "style-color" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>