config/routes.rb
Rails.application.routes.draw do

  # ユーザー側
  # URL /customers/sign_in ...
  devise_for :user,skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # ゲストユーザー側
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    # get 'user', to: 'public/registrations#new'
  end

  # 管理者側
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }

  # ユーザー側
  scope module: :public do
    root to: 'homes#top'
    get 'group_messages/create'
    get '/about' => 'homes#about'
    get '/genre/search' => 'music_posts#index'
    # お問い合わせ
    resources :contacts, only: [:new, :index, :create]
    # 探究室
    resources :labos, only: [:index, :show, :create, :update, :destroy] do
      resources :labo_comments, only: [:create,:destroy]
    end
    # tagと紐づけを行うためのlabo
    resources :tags do
      member do
        get :labos
        delete :labo
      end
    end

    # 音楽共有
    resources :music_posts, only: [:index, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only: [:index, :create, :destroy]
      resources :music_post_comments, only:[:create, :destroy, :update]
    end

    # ユーザー情報

    resources :users, only: [:show, :edit, :update, :index] do
      # 退会確認画面
      get 'confirm', on: :member
      # フォロー・フォロワー
      member do
        get 'followings'
        get 'followers'
      end

      # ユーザー検索用
      # コレクションの中に入れることでidを渡さずにパスを生成してくれる
      collection do
        get 'search'
         # 論理削除用のルーティング
        patch  'withdraw'
      end
      # いいね一覧表示
      member do
        get 'favorites'
      end
      post 'user_music_posts', to: 'user_music_mosts#create', as: 'user_music_posts'

      resources :nikos, only: [:create, :update, :destroy]
      resource :relationships, only: [:create, :destroy]
    end
    # グループ
    resources :groups, only: [:index, :show, :create, :update, :edit, :create, :destroy] do
      get 'join' => 'groups#join'
      delete 'leave', on: :member
      resources :group_user_comments, only: [:create, :destroy]
    end
  end

  # 管理者側
  namespace :admin do
    root to: 'homes#top'
    # 検索用
    get '/search' => 'homes#search'
    # お問い合わせ
    resources :contacts, only: [:index, :show]
    # 会員情報
    resources :users, only: [:index, :show, :edit, :destroy, :update] do
      resources :user_post_comments, only: [:index, :destroy]
      get '/comments' => 'user_comments#comment'
      member do
        patch '/comments' => 'comments#update'
        delete '/comments' => 'comments#destroy'
      end
    end
    # グループ
    resources :groups do
      resources :group_users, only: [:index] do
        delete 'destroy', to: 'group#destroy', as: 'group_destroy'
        resources :group_user_comments, only: [:index, :show, :destroy]
      end
    end
    # 探究室コメント
    resources :labos, only: [:index, :show, :create, :update, :destroy] do
      resources :labo_comments, only: [:index, :destroy, :show]
    end
    #resources :labo_comments, only: [:index, :show, :destroy]
    # タグ一覧・作成
    resources :tags, only: [:index, :create, :edit, :update, :destroy] do
      delete 'destroy_all', on: :collection
    end
    # 音楽共有
    resources :music_posts, only: [:index, :show, :destroy] do
      resources :music_post_comments, only:[:index, :destroy]
    end
    #resources :music_post_comments, only: [:index, :show, :destroy]
  end
end

app/models/music_post.rb
class MusicPost < ApplicationRecord

  # ユーザーと紐づけ
  belongs_to :user

  # この投稿に関連するお気に入りの情報を取得する
  has_many :favorites, dependent: :destroy

  # この投稿に関連するコメントの情報を取得する
  has_many :music_post_comments, dependent: :destroy

  # この投稿に関連する画像をAI画像認識の情報を取得する
  has_many :ai_tags, dependent: :destroy

  # 投稿画像
  has_one_attached :image
  # タイトルと投稿文設定
  validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }

  # この投稿をお気に入りに追加しているかどうかを確認する
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # この投稿のお気に入りの数を取得する
  def favorites_count
    favorites.count
  end

  # タイトル検索機能
  def self.search_for(content, method)
    if method == 'perfect'
      Music_post.where(title: content)
    elsif method == 'forward'
      Music_post.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Music_post.where('title LIKE ?', '%' + content)
    else
      Music_post.where('title LIKE ?', '%' + content + '%')
    end
  end

  # ソート機能
  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    when 'likes'
      return find(Favorite.group(:music_post_id).order(Arel.sql('count(music_post_id) desc')).pluck(:music_post_id))
    when 'dislikes'
      return find(Favorite.group(:music_post_id).order(Arel.sql('count(music_post_id) asc')).pluck(:music_post_id))
    end
  end

  # 画像を選択していたら表示
    def get_music_post_image
      self.image.attached? ? self.image : 'no-image-icon.jpg'
    end

end

app/controllers/admin/music_posts_controller.rb
class Admin::MusicPostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @music_posts = MusicPost.all
    @music_post_page = MusicPost.page(params[:page])
  end

  def show
    @music_post = MusicPost.find(params[:id])
    @music_post_comments = @music_post.music_post_comments
    @user = @music_post.user
  end

  def destroy
    @music_post = MusicPost.find(params[:id])
    @music_post.destroy
    redirect_to admin_music_posts_path, notice: "音楽共有の投稿を削除しました。"
  end
end

app/views/admin/music_posts/index.html.erb
<div class="container my-4 pb-5">
  <div class="row justify-content-start mb-2">
    <h5 class="style-title">音楽共有一覧</h5>
  </div>
  <div class="row custom-background">
    <div class="col-2 text-center mt-2">
      <h5>日付</h5>
    </div>
    <div class="col-4 text-left mt-2">
      <h5>タイトル</h5>
    </div>
    <div class="col mt-2 text-left mr-2">
      <h5>投稿文</h5>
    </div>
  </div>

  <% @music_posts.each do |music_post| %>
  <div class="row custom-table-striped border border-danger">
    <div class="col-2 text-center mt-2">
      <%= music_post.created_at.strftime('%Y/%m/%d') %>
    </div>
    <div class="col-4 text-left mt-2">
      <%= link_to music_post.title, admin_music_post_path(music_post.id), class: "style-color" %>
    </div>
    <div class="col mt-2 text-left mr-2">
      <%= music_post.body %>
    </div>
  </div>
  <% end %>
  <%#= paginate @music_posts %>
</div>

app/views/admin/music_posts/show.html.erb
<!--音楽共有の投稿詳細-->
<div class="container my-4 pb-5 admin-top">
  <div class="row justify-content-start mb-3">
    <h5 class="style-title">会員ID:<%= @user.id %> <%= @user.nickname %> さんの音楽共有投稿内容</h5>
  </div>

  <div class="row custom-background">
    <div class="col-2"></div>
    <div class="col-4 text-left mt-2">
      <h5>タイトル</h5>
    </div>
    <div class="col text-left mt-2">
      <h5>投稿内容</h5>
    </div>
  </div>

  <div class="row d-flex align-items-center justify-content-centerborder border border-danger">
    <div class="col-2 my-3">
      <%= image_tag @user.get_profile_image, class: "rounded-circle", size:'100x100' %>
    </div>
    <div class="col-4 text-left">
      <%= @music_post.title %>
    </div>
    <div class="col text-left">
      <%= @music_post.body %>
    </div>
  </div>
  <div class="row  my-3">
    <div class="col text-right">
      <%= link_to "投稿削除", admin_music_post_path(@music_post.id), method: :delete, class: "btn btn-danger", data: {confirm: "本当に削除しますか？" }, remote: true  %>
    </div>
  </div>

  <div class="row my-3">
    <div class="col text-right">
      <%= link_to "音楽共有一覧へ戻る", admin_music_posts_path, class: "btn text-white admin-style-color01" %>
    </div>
  </div>

<!--探究室の投稿コメントが表示される-->
<% if @music_post.music_post_comments.exists? %>
  <div class="row justify-content-start my-4">
    <h5 class="style-title">投稿のコメント</h5>
  </div>
  <div class="row mt-2 custom-background">
    <div class="col-2"></div>
    <div class="col text-center mt-1">
      <h5>コメント</h5>
    </div>
    <div class="col-2 mt-1 admin-style-block" style="display: block;">
      <h5>会員</h5>
    </div>
  </div>

  <div class="row d-flex align-items-center justify-content-centerborder border border-danger">
  <% @music_post_comments.each do |music_post_comment| %>
    <div class="col-12 custom-table-striped border border-danger">
      <div class="row my-1">
        <div class="col-3 text-left ml-2 d-flex align-items-center">
          <%= link_to "コメント削除", admin_music_post_music_post_comment_path(music_post_comment.music_post, music_post_comment), method: :delete, class: "btn btn-danger", data: { confirm: "本当に削除しますか？" }, remote: true %>
        </div>
        <div class="col text-left d-flex align-items-center">
          <%= music_post_comment.comment %>
        </div>
        <div class="col-2 mr-auto flex-colmum my-3">
          <%= image_tag music_post_comment.user.get_profile_image, class: "rounded-circle", size: "50x50" %>
          <div class="flex-colmum text-center">
            <%= link_to music_post_comment.user.nickname, admin_user_path(music_post_comment.user), class: "style-color" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% else %>
  <div class="row justify-content-center my-5">
    <h5 class="admin-style-color"><b><%= @music_post.user.nickname %></b>　さんの投稿にはコメントはありません。</h5>
  </div>
<% end %>
</div>