config/routes.rb
Rails.application.routes.draw do

  # ユーザー側
  # URL /customers/sign_in ...
  devise_for :user,skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # ゲストユーザー側
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    # get 'user', to: 'public/registrations#new'
  end

  # 管理者側
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }

  # ユーザー側
  scope module: :public do
    root to: 'homes#top'
    get 'group_messages/create'
    get '/about' => 'homes#about'
    get '/genre/search' => 'music_posts#index'
    # お問い合わせ
    resources :contacts, only: [:new, :index, :create]
    # 探究室
    resources :labos, only: [:index, :show, :create, :update, :destroy] do
      resources :labo_comments, only: [:create,:destroy]
    end
    # tagと紐づけを行うためのlabo
    resources :tags do
      member do
        get :labos
        delete :labo
      end
    end

    # 音楽共有
    resources :music_posts, only: [:index, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only: [:index, :create, :destroy]
      resources :music_post_comments, only:[:create, :destroy, :update]
    end

    # ユーザー情報

    resources :users, only: [:show, :edit, :update, :index] do
      # 退会確認画面
      get 'confirm', on: :member
      # フォロー・フォロワー
      member do
        get 'followings'
        get 'followers'
      end

      # ユーザー検索用
      # コレクションの中に入れることでidを渡さずにパスを生成してくれる
      collection do
        get 'search'
         # 論理削除用のルーティング
        patch  'withdraw'
      end
      # いいね一覧表示
      member do
        get 'favorites'
      end
      post 'user_music_posts', to: 'user_music_mosts#create', as: 'user_music_posts'

      resources :nikos, only: [:create, :update, :destroy]
      resource :relationships, only: [:create, :destroy]
    end
    # グループ
    resources :groups, only: [:index, :show, :create, :update, :edit, :create, :destroy] do
      get 'join' => 'groups#join'
      delete 'leave', on: :member
      resources :group_user_comments, only: [:create, :destroy]
    end
  end

  # 管理者側
  namespace :admin do
    root to: 'homes#top'
    # 検索用
    get '/search' => 'homes#search'
    # お問い合わせ
    resources :contacts, only: [:index, :show]
    # 会員情報
    resources :users, only: [:index, :show, :edit, :destroy, :update] do
      resources :user_post_comments, only: [:index, :destroy]
      get '/comments' => 'user_comments#comment'
      member do
        patch '/comments' => 'comments#update'
        delete '/comments' => 'comments#destroy'
      end
    end
    # グループ
    resources :groups do
      resources :group_users, only: [:index] do
        delete 'destroy', to: 'group#destroy', as: 'group_destroy'
        resources :group_user_comments, only: [:index, :show, :destroy]
      end
    end
    # 探究室コメント
    resources :labos, only: [:index, :show, :create, :update, :destroy] do
      resources :labo_comments, only: [:index, :destroy, :show]
    end
    #resources :labo_comments, only: [:index, :show, :destroy]
    # タグ一覧・作成
    resources :tags, only: [:index, :create, :edit, :update, :destroy] do
      delete 'destroy_all', on: :collection
    end
    # 音楽共有
    resources :music_posts, only: [:index, :show, :destroy] do
      resources :music_post_comments, only:[:index, :destroy]
    end
    #resources :music_post_comments, only: [:index, :show, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  # 二胡の情報
  has_many :nikos, dependent: :destroy
  # 音楽共有投稿
  has_many :music_posts, dependent: :destroy
  # 音楽共有コメント（中間テーブル）
  has_many :music_post_comments, dependent: :destroy
  # グループ
  has_many :groups, dependent: :destroy
  # ユーザーグループ（中間テーブル）
  has_many :group_users, dependent: :destroy
  # 画像持たせる
  has_one_attached :profile_image
  # グループ内コメント
  has_many :group_user_comments, dependent: :destroy
  # お気に入り（中間テーブル）
  has_many :favorites, dependent: :destroy
  # 探究室
  has_many :labos, dependent: :destroy
  # 探究室コメント
  has_many :labo_comments, dependent: :destroy

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :follow

  has_many :labo_comments
  # お問い合わせ
  has_many :contacts

  # 名前と自己紹介文の設定
  validates :nickname, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # 性別の選択設定
  enum gender: { man: 1, woman: 2, other: 3, noinput: 9 }

  # ゲストログイン設定
  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "guestuser" # ニックネームの属性を設定
    end
  end

  # メールアドレスがゲストユーザーのものであるかの判定
  def guest_user?
    email == GUEST_USER_EMAIL
  end


  # 会員ステータス
  def user_status
    is_active ? "有効" : "退会"
  end
  
  # 退会しているuserが同じアカウントでログインできないようにする
  def active_for_authentication?
    super && is_active?
  end

    # 画像の情報
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # 検索機能の情報　ニックネーム
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(nickname: content)
    elsif method == 'forward'
      User.where('nickname LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('nickname LIKE ?', '%' + content)
    else
      User.where('nickname LIKE ?', '%' + content + '%')
    end
  end

  # 指定したユーザーをフォローする
  def follow(user)
    relationships.create(follow_id: user.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    relationships.find_by(follow_id: user.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:search]
      @users = User.where('nickname LIKE ?', "%#{params[:search]}%")
      @user_page = User.page(params[:page])
    else
      @users = User.all
      @user_page = User.page(params[:page])
    end
  end

  def show
    @user = User.find(params[:id])
    @music_posts = @user.music_posts
  end

  def edit
    @user = User.find(params[:id])
    @niko = @user.nikos.find_by(id: params[:niko_id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "会員情報が更新されました。"
    else
    render "edit"
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user
      @user.update(introduction: nil)
      flash[:notice] = "正常に削除できました。"
    end
    redirect_to admin_user_path(@user)
  end

  def comment
    @labos = Labo.all
    @music_posts = MusicPost.all
    @user = User.find(params[:user_id])
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :is_active, :introduction, :profile_image)
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container my-4 pb-5">
  <div class="row">
    <h5 class="style-title"><%= @user.nickname %>さんの会員情報編集</h5>
  </div>

  <div class="row text-left my-3 ml-3">
    <%= image_tag @user.get_profile_image, size: "200x150", class: "custom-border" %>
    <div class="col offset-3">
      <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
      <div class="row my-3">
        <div class="col-3">
          <%= link_to "詳細へ戻る", admin_user_path(@user.id), class: "btn text-white admin-style-user-btn01" %>
        </div>
        <div class="col text-right">
         <%= link_to "投稿の詳細", admin_user_comments_path(@user.id), class: "btn text-white admin-style-user-btn02" %>
       </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>会員ＩＤ</h5>
        </div>
        <div class="col">
          <h5><%= @user.id %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>ニックネーム</h5>
        </div>
        <div class="col">
          <h5><%= @user.nickname %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>生年月日</h5>
        </div>
        <div class="col">
          <h5><%= @user.birthdate %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>性別</h5>
        </div>
        <div class="col">
          <h5><%= @user.gender_i18n %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>メールアドレス</h5>
        </div>
        <div class="col">
          <h5><%= @user.email %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>自己紹介文</h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <%= f.text_area :introduction, class: "form-control introduction mb-2" %>
        </div>
      </div>

      <div class="row my-2">
       <div class="col text-right">
         <%= link_to "コメント削除", admin_user_path(@user), method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-sm btn-danger" %>
       </div>
      </div>

      <div class="row my-3">
        <div class="col">
          <h5>会員ステータス</h5>
        </div>
        <div class="col">
        <% unless @user.guest_user? %>
          <%= f.radio_button :is_active, true, id: "active_true" %>
          <%= f.label :is_active, "有効", for: "active_true" %>
          <%= f.radio_button :is_active, false, id: "active_false" %>
          <%= f.label :is_active, "退会", for: "active_false" %>
        <% else%>
          <h5>ゲストは変更不可</h5>
        <% end %>
        </div>
      </div>

      <div class="row my-2">
        <div class="col text-right">
          <%= f.submit "変更を保存", class: "btn btn-outline-secondary mb-2 mx-5" %>
        </div>
      </div>
      <% end %>

      <% if @user.nikos.present? %>
      <div class="row">
        <div class="col">
          <h5 class="admin-style-user-niko">
            <span class="bg-highlight">My二胡の情報編集</span>
          </h5>
        </div>
      </div>

      <% @user.nikos.each do |niko| %>
        <div class="custom-table-striped border border-danger">
          <div class="row  my-3 ml-2">
            <div class="col-3">
              名前
            </div>
            <div class="col">
              <h5><%= niko.name %></h5>
            </div>
          </div>

          <div class="row my-2 ml-2">
            <div class="col-3 now-nowrap">
              使われた木材
            </div>
            <div class="col">
              <h5><%= niko.tree_type_i18n %></h5>
            </div>
          </div>

          <div class="row my-2 ml-2">
            <div class="col-3">
              特徴
            </div>
            <div class="col">
              <%= niko.feature %>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container my-4 pb-5 admin-top">
  <div class="row justify-content-start mb-2">
      <h5 class="style-title">会員一覧</h5>
  </div>
  <div class="row custom-background">
    <div class="col-2 mt-2">
      <h5>会員ID</h5>
    </div>
    <div class="col mt-2">
      <h5>氏名</h5>
    </div>
    <div class="col mt-2">
      <h5>メールアドレス</h5>
    </div>
    <div class="col-2 mt-2 now-nowrap">
      <h5>ステータス</h5>
    </div>
  </div>

    <% @users.each do |user| %>
    <div class="row custom-table-striped border border-danger">
      <div class="col-2 my-2 text-center">
        <h5><%= user.id %></h5>
      </div>
      <div class="col my-2 text-center">
        <h5><%= link_to user.nickname, admin_user_path(user.id), class: "style-color" %></h5>
      </div>
      <div class="col my-2">
        <h5><%= user.email %></h5>
      </div>
      <div class="col-2 my-2 text-center">
        <div>
          <% if user.user_status == "有効" %>
          <span class="text-success font-weight-bold"><%= user.user_status%></span>
          <% else %>
          <span class="text-danger font-weight-bold"><%= user.user_status %></span>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>

  <div class="d-flex justify-condivnt-cendivr">
    <%#= paginate @user_page %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container my-4 pb-5">
  <div class="row">
    <h5 class="style-title"><%= @user.nickname %>さんの会員情報詳細</h5>
  </div>

  <div class="row text-left my-3 ml-3">
      <%= image_tag @user.get_profile_image, size: "200x150", class: "custom-border" %>
    <div class="col offset-3">
      <div class="row my-2">
        <div class="col">
          <h5>会員ＩＤ</h5>
        </div>
        <div class="col">
          <h5><%= @user.id %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>ニックネーム</h5>
        </div>
        <div class="col">
          <h5><%= @user.nickname %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>生年月日</h5>
        </div>
        <div class="col">
          <h5><%= @user.birthdate %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>性別</h5>
        </div>
        <div class="col">
          <h5><%= @user.gender_i18n %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>メールアドレス</h5>
        </div>
        <div class="col">
          <h5><%= @user.email %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>自己紹介文</h5>
        </div>
        <div class="col">
          <h5><%= @user.introduction %></h5>
        </div>
      </div>

      <div class="row my-2">
        <div class="col">
          <h5>会員ステータス</h5>
        </div>
        <div class="col">
          <% if @user.is_active? %>
            <span class='text-success'>有効</span>
          <% else %>
            <span class='text-secondary'>退会</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row my-4">
    <div class="col">
      <%= link_to '一覧に戻る', admin_users_path, class: "btn text-white admin-style-user-show01" %>
    </div>
    <div class="col">
      <%= link_to '編集', edit_admin_user_path(@user.id), class: "btn text-white admin-style-user-show02" %>
    </div>
  </div>
</div>